name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      # Will be added later on
      #      - name: Run tests
      #        run: npm test -- --coverage

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t sveltos-dashboard-ui:latest .
